version: "3.8"
services:
  nodeapp:
    build:
      context: ./node-module
      dockerfile: Dockerfile
    container_name: node-api
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: jacob
      DB_PASSWORD: Password123!
      DB_NAME: test
    ports:
      - "3000:3000"

  pythonapi:
    build:
      context: ./python-module
      dockerfile: Dockerfile
    container_name: python-api
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: jacob
      DB_PASSWORD: Password123!
      DB_NAME: test
    ports:
      - "5050:5000"

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: jacob
      POSTGRES_PASSWORD: Password123!
      POSTGRES_DB: test
    ports:
      - "5416:5432"
